language: node_js
node_js:
  - '4.0'
  - '0.10'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g karma karma-jasmine karma-phantomjs-launcher karma-firefox-launcher

script:
  - karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
